# Generated by Django 5.1.6 on 2025-03-03 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color1', models.CharField(max_length=7)),
                ('color2', models.CharField(max_length=7)),
                ('color3', models.CharField(max_length=7)),
                ('color4', models.CharField(max_length=7)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaletteLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palettelike', to='palette.palette')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('palette', 'user')},
            },
        ),
        migrations.AddField(
            model_name='palette',
            name='like',
            field=models.ManyToManyField(related_name='likes', through='palette.PaletteLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
