# Generated by Django 5.1.6 on 2025-03-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palette',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
